config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "search", to: "pages#search"
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :description, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = current_user&.articles&.order(created_at: :desc)&.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    fetch_metadata(@article) if @article.url.present?

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    # Update the article with the new URL first
    if article_params[:url].present?
      @article.assign_attributes(article_params)
      fetch_metadata(@article)
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :url, :og_image, :og_description, :og_title, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own articles"
        redirect_to @article
      end
    end

    def fetch_metadata(article)
      require 'open-uri'
      require 'nokogiri'
    
      begin
        Rails.logger.debug "Fetching metadata for URL: #{article.url}"
        # Set a user-agent header to mimic a browser request
        options = {
          "User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
        }
        doc = Nokogiri::HTML(URI.open(article.url, options))
        
        # Fetch og:title and assign it to description if present
        og_title = doc.at('meta[property="og:title"]')&.[]('content')
        article.og_title = og_title
        # article.description = og_title || doc.at('title')&.text
        Rails.logger.debug "Fetched description (og:title): #{article.description}"
        
        # Fetch og:image
        article.og_image = doc.at('meta[property="og:image"]')&.[]('content')
        article.og_image ||= doc.at('#landingImage')&.[]('src')
        Rails.logger.debug "Fetched og_image: #{article.og_image}"
        
        # Fetch og:description
        article.og_description = doc.at('meta[property="og:description"]')&.[]('content')
        Rails.logger.debug "Fetched og_description: #{article.og_description}"
      rescue OpenURI::HTTPError => e
        Rails.logger.error "HTTP Error: #{e.message}"
      rescue StandardError => e
        Rails.logger.error "Error fetching metadata: #{e.message}"
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="card p-3 bg-dark">
  <div class="card-body p-0">
          <% if article.categories.any? %>
        <div class="mb-2">
          <% article.categories.each do |category| %>
            <%= link_to category.name, category_path(category), class: "badge bg-secondary" %>
          <% end %> 
        </div>
      <% end %>
    <div class="d-flex flex-row justify-content-between">
      <% if article.user.present? %>
      <div>
       From: <%= article.user.username %></span>
        </div>
      <% end %>
      <% if article.title.present? %>
        <div>
          <h6 class="text-sm text-muted">Titulli</h6>
          <h5 class="card-title d-inline">
            <%= article.title %>
          </h5>
        </div>
      <% end %>
      <h6 class="d-inline text-end">
        <%= article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
      </h6>
    </div>
    <div class="mt-3">
      <h6 class="text-muted">Details:</h6>
        <h5>
      <%= article.description %>
    </h5>
    </div>
  </div>
  <div class="d-flex align-items-center gap-2 w-100 mt-1 gap-2">
    <% if logged_in? && (current_user == article.user || article.user.admin?)  %>
      <%= link_to "See more", article_path(article), class: "d-inline" %>
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning ml-auto" %>
      <div>
        <button type="button" class="btn btn-danger ml-auto" data-bs-toggle="modal" data-bs-target="#exampleModal" data-article-id="<%= article.id %>">
          Delete
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <%= render 'shared/errors' %>
  <div class="form-row">
    <div class="form-group mb-3">
      <%= form.label "Your wish:", for: "description", class: "form-label" %>
      <%= form.text_area :description, class: "form-control", id: "description", rows: 5 %>
    </div>
    <hr>
    <div class="form-group mb-3">
      <%= form.label "Link:", for: "url", class: "form-label" %>
      <%= form.text_field :url, class: "form-control", id: "url", placeholder: "Enter a URL" %>
    </div>
    <div class="form-group mb-3">
      <%= form.label "Category:", for: "category", class: "form-label" %>
      <%= form.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below" }, { multiple: true, class: "custom-select" }) %>
    </div>
    <div>
      <%= form.submit article.new_record? ? "Create wish" : "Edit wish", class: "btn btn--link mt-2" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to your wish", @article %> |
  <%= link_to "Wishlist", articles_path %>
</div>

app/views/articles/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<h1>Wishlist</h1>
<%= link_to "Create a wish", new_article_path, class: "btn--link mt-3 rounded" %>
<div id="articles" class="d-flex flex-column gap-3 mt-4">
  <% @articles&.each do |article| %>
    <%= render article %>
  <% end %>
</div>

<% if @articles %>
<%= will_paginate @articles, class: "apple_pagination" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create</h1>
<%= render "form", article: @article %>
<br>
<div>
  <%= link_to "Back to Wishlist", articles_path %>
</div>

app/views/articles/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<h1>Wish: #<%= @article.id %></h1>
<hr>
  <h6 class="mt-3">Detajet</h6>
  <h5>
    <%= @article.description %>
  </h5>
  <h6 class="mt-3">Koha e krijimit</h6>
  <h5>
    <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </h5>
<% if @article.og_title.present? || @article.og_image.present? || @article.og_description.present? %>
  <h5 class="mt-3">Prej linkut:</h5>
<% end %>
<% if @article.og_title.present? %>
  <h5><%= @article.og_title %></h5>
<% end %>
<% if @article.og_image.present? %>
  <img class="og-image" src="<%= @article.og_image %>" alt="OG Image">
<% end %>
<% if @article.og_description.present? %>
  <p><%= @article.og_description %></p>
<% end %>
</div>
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
<hr>
<div class="d-flex flex-row gap-2 mt-3">
  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-warning" %>
  <div>
    <button type="button" class="btn btn-danger ml-auto" data-bs-toggle="modal" data-bs-target="#exampleModal" data-article-id="<%= @article.id %>">
      Delete
    </button>
  </div>
</div>
<% end %>
<hr>
<div>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Create another wish", new_article_path, class: "btn btn-light" %>
  <% end %>
  <%= link_to "Back to wishes", articles_path, class: "btn btn-dark" %>
</div>