config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "search", to: "pages#search"
  resources :categories, except: [:destroy]
end

app/views/pages/about.html.erb
<h1>How to use wishlist.com?</h1>
<p class="mt-3">
  The wishlist is a simple web application that allows you to create and view your wishes.
</p>
<p>
  At the top of the page, you will find a link to return to the homepage, a link to go to the wishlist, and a link to this page.
</p>
<p>
  On the homepage, you will see your wishlist. For each wish, you will see the description and the creation time. For each wish, you will have the option to view details, edit the wish, and delete the wish.
</p>

app/views/pages/home.html.erb
<%= render 'shared/notice' %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div>
<div class="d-flex flex-column">
  <h1>Home</h1>
  <p>This website is created to help in finding the wishes of different people.</p>
</div>
</div>
<div class="d-flex flex-column md-flex-row gap-3 md-align-items-start">
<%# <div> %>
  <%# link_to "View your wishes", articles_path, class: "btn btn-dark" %>
  <%# link_to "View users", users_path, class: "btn btn-light" %>
  <%# link_to "Create a wish", new_article_path, class: "btn btn-warning" %>
<%# </div> %>
<% if @users.any? %>
  <div style="flex: 1;">
    <%= form_tag search_path, method: :get, class: "d-flex mb-4" do %>
      <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Search for user or wish" %>
      <%= submit_tag "Search", class: "btn btn-success" %>
    <% end %>
  </div>
<% end %> 
</div>
<% if @users.any? %>
  <div class="mt-4 users-container">
    <h2 class="mb-0">Latest users created</h2>
      <hr>
      <div class="d-flex flex-column users-home">
        <% @users.each do |user| %>
          <%= render user %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/search.html.erb
<!-- filepath: /Users/erindhoxha/Documents/prjcts/store/app/views/pages/search.html.erb -->
<h1>Search Results</h1>

<%= form_tag search_path, method: :get, class: "d-flex mb-4" do %>
  <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Search for user or wish" %>
  <%= submit_tag "Search", class: "btn btn-success" %>
<% end %>

<% if @users.any? %>
  <h2>Users</h2>
  <hr>
  <div id="users" class="d-flex flex-column">
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </div>
<% else %>
<hr>
  <p class="mt-3">No users found.</p>
<% end %>

<% if @articles.any? %>
  <h2 class="mt-3">Wishes</h2>
<hr>
  <div id="wishes" class="d-flex flex-column">
    <% @articles.each do |article| %>
      <%= render article %>
    <% end %>
  </div>
<% else %>
<hr>
  <p class="mt-3">No wishes found.</p>
<% end %>