config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "search", to: "pages#search"
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
 validates :name, presence: true, length: { minimum: 3, maximum: 50 }
 validates_uniqueness_of :name
 has_many :article_categories
 has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully!"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if (@category.save)
      flash[:notice] = "Category was created successfully."
      redirect_to @category
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
   <% if @category.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "form-label", for: "name" %>
    <%= form.text_field :name, class: "form-control", id: "name", placeholder: "Enter name" %>
  </div>
  <div>
    <%= form.submit category.new_record? ? "Create" : "Edit", class: "btn btn-success mt-3" %>
  </div>
<% end %>

app/views/categories/_user.html.erb
<div id="<%= dom_id user %>">
  <div class="d-flex align-items-center">
    <%= link_to user_path(user), class: "d-flex flex-row gap-3 align-items-center mb-4 title-link" do %>
    <%= gravatar_for user %>
    <div class="mb-0">
      <h4 class="mb-0">
        <%= user.username %>
      </h4>
    </div>
    <% end %>
    <% unless controller_name == 'users' && action_name == 'show' %>
      <p class="mb-0 ml-auto">
        <%= link_to "View", user, class: "btn btn-light" %>
      </p>
    <% end %>
  </div>
  <h5>Wishlist (<%= user.articles.count %>):</h5>
<div class="d-flex flex-column gap-3">
  <% if user.articles.any? %>
    <div class="gap-3 d-flex flex-column">
      <% user.articles.order(created_at: :desc).each do |article| %>
        <%= render article %>
      <% end %>
    </div>
  <% else %>
    <p class="mb-0">No wishes available.</p>
  <% end %>
</div>
</div>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render "form", category: @category %> 

app/views/categories/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<h1>Categories</h1>
<div id="articles" class="d-flex flex-column gap-3 mt-4">
  <% @categories&.each do |category| %>
    <a href="<%= category_path(category) %>" class="category-link">
      <div class="category-item p-3 border rounded">
        <h3><%= category.name %></h3>
        <p><%= pluralize(category.articles.count, 'article') %></p>
      </div>
    </a> 
  <% end %>
</div>

<% if @categories %>
<%= will_paginate @categories, class: "apple_pagination" %>
<% end %>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= render "form", category: @category %> 

app/views/categories/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>


<div class="d-flex flex-column md-flex-row gap-3 md-align-items-end">
  <h1>Category: <%= @category.name %></h1>
  <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-warning mb-2" %>
</div>
  <p class="mb-0">Total wishes: <%= pluralize(@category.articles.count, 'wish') %></p>
<hr>
<div id="articles" class="d-flex flex-column gap-3 mt-4">
  <% @category.articles&.each do |article| %>
    <%= render article %>
  <% end %>
</div>