config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "search", to: "pages#search"
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="container d-flex flex-wrap justify-content-between align-items-center py-3 my-3 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2025 Wishlist, Inc</p>
    <ul class="nav col-md-4 justify-content-end">
      <%# <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li> %>
    </ul>
  </footer>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-light bg-light navbar-expand-lg">
  <div class="container">
    <%= link_to "Wishlist.io", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Find people", users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Your wishes", articles_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "View all", categories_path, class: "dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <hr class="my-2">
          <div class="md-ml-auto d-flex flex-column md-flex-row">
              <li class="nav-item dropdown md-ml-auto">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= "(Admin)" if current_user.admin? %> Profile: [<%= current_user.username %>]
                </a>
                <ul class="dropdown-menu">
                  <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Delete profile", user_path(current_user), method: :delete, class: "dropdown-item text-danger", data: { confirm: "Are you sure?" } %>
                </ul>
              </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
          </div>
        <% else %>
          <hr class="my-2">
          <div class="md-ml-auto d-flex flex-column md-flex-row">
              <li class="nav-item">
                <%= link_to "Register", signup_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
            </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render "layouts/navbar" %>
    <%= render "shared/articles_confirmation_modal" %>
    <section class="container mt-4 h-100">
      <%= yield %>
      <%= render "layouts/footer" %>
    </section>
  </body>
</html>